[package]
name = "anemone"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
colored = "2.0.0"
cargo-bump = "1.1.0"
pulldown-cmark = "0.9.1"
filetime = "0.2"